server:
  port: 9095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://loschachos:qwerty12345@cluster0.ulmgvow.mongodb.net/
      repositories:
        enabled: true
